name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  rename: ^3.1.0

flutter:
  uses-material-design: true

  # 앱에서 사용할 자산(파일)들을 등록하는 곳입니다.
  assets:
    - .env
    - assets/icon/

# 앱 아이콘 생성 설정
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  # 안드로이드 8.0 이상을 위한 적응형 아이콘 설정 (필요시 사용)
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icon/app_icon.png"